# Generated by Django 3.0.4 on 2020-03-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_studentlogin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='stinfo',
        ),
    ]
